### Project location
rewriteBase: /hubleto-webinar/
projectUrl: http://localhost/{{ rewriteBase }}
srcUrl: http://localhost/{{ rewriteBase }}/vendor/hubleto/erp
assetsUrl: http://localhost/{{ rewriteBase }}/vendor/hubleto/assets

### Database connection
dbHost: localhost
dbUser: hubleto
dbPassword: ''
dbName: hbl_dev
dbCodepage: utf8mb4

### Initial account access
accountFullName: Hubleto DEV
adminName: DEV
adminFamilyName: Hubleto
adminNick: admin
adminEmail: dev@example.com
adminPassword: dev
packagesToInstall: crm,marketing,sales,projects,retail,e-commerce,finance,developer

### Miscellaneous
generateDemoData: true
noPrompt: true

### Apps to be installed
# Uncomment following lines if you want to have full control over what
# apps will be installed. Example below installs minimal set of apps.
# CAUTION: order of the apps is important
appsToInstall:
   Hubleto\App\Custom\CarRental: []
#   Hubleto\App\Community\Tools: []
#   Hubleto\App\Community\Desktop: []
#   Hubleto\App\Community\Usage: []

### Extra config parameters
# Uncomment following lines if you want to customize look & feel
# of your Hubleto
# extraConfigEnv:
#   uiTheme: green-orange
#   logoUrl: assets/custom/images/my-hubleto.png
#   welcomeSplashImageUrl: assets/custom/images/my-hubleto.png
#   availableLanguages: []
#   appTitle: My Hubleto - Fully customized Hubleto
#   sidebarGroups:
#     crm:
#       title: CRM
#       icon: fas fa-id-card-clip
#     maintenance:
#       title: Maintenance
#       icon: fas fa-cog
